### ISSUE TITLE
Download only original size?

### ISSUE THREAD

**Issue by smcgivern** [aaronpk/Flickr-Archivr#1]
Thanks for putting this together, I've been looking for something like this for a while!

This line in the README intrigued me:

> Make sure you have enough disk space in the chosen location! For reference, Flickr says I have 120gb of photos, and once this script downloaded all the different resolutions, it took 255gb on disk.

I see that we download all the sizes of a photo here: https://github.com/aaronpk/Flickr-Archivr/blob/8d8d20a195b79e0d111fd06618e2be6d62034a60/lib/flickr.php#L139-L162

Would you accept a patch that adds an option to only download the original (maximum) size? It's not clear to me why we want the other sizes anyway, especially if the cost in disk space is so high.

**Comment by aaronpk** [comment]
Yes I'm open to a patch for that!

The reason to download the smaller sizes is because this also builds a website so you can browse the archive and it uses the smaller sizes for the previews on the site.

**Comment by smcgivern** [comment]
Thanks for the context! If we only need the original and the Large Square size for the thumbnail, we could also grab just those? https://github.com/aaronpk/Flickr-Archivr/blob/8d8d20a195b79e0d111fd06618e2be6d62034a60/scripts/buildsite.php#L67

Anyway, I'll just focus on originals for now as that covers my use case (I'm mainly interested in downloading everything).
